### ISSUE TITLE
Home screen map loses context when settings or location details screen is displayed

### ISSUE THREAD

**Issue by davecraig** [Scottish-Tech-Army/Soundscape-Android#136]
To reproduce:

1. Run the application
2. Navigate to the Settings screen from the Menu drawer
3. Return to the Home screen

The map is zoomed out to the world. Stopping and restarting the service by clicking on the location icon in the top right hand corner twice restores the map zoom and location.

The Home page map currently uses an Android compatibility view to wrap maplibre rendering in Jetpack compose. Moving to use a Jetpack compose maplibre library such as [ramani-maps](https://github.com/ramani-maps/ramani-maps) or [maplibre-compose](https://github.com/Rallista/maplibre-compose-playground) might be a good step, though those seem fairly early on in development.

**Comment by FannyDemey** [comment]
@davecraig i'll have a look at this one. It sounds like a lifecycle issue or something related to a recomposition of the screen that implies the reset of the map, that should not occur.
